version: '3.8'

services:
  job-application-api:
    container_name: jobapplicationapi
    build:
      context: ./JobApplicationSystem
      dockerfile: ./JobApplicationSystem/Dockerfile
    image: job-application-api
    ports:
      - "8000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    restart: always